var punsarray = Array(
  "Why did the scarecrow win an award? Because he was outstanding in his field.",
  "Why did the melon jump into the lake? It wanted to be a water-melon.",
  "How does the ocean say hello? It waves.",
  "What creature is smarter than a talking parrot? A spelling bee.",
  "Apparently, you can’t use “beef stew” as a password. It’s not stroganoff.",
  "Why did the drum take a nap? It was beat.",
  "Where do hamburgers go dancing?  They go to the meat-ball.",
  "Why did the tomato turn red?  It saw the salad dressing.",
  "Why shouldn’t you write with a broken pencil? Because it’s pointless.",
  "What do you call two monkeys that share an Amazon account? Prime mates.",
  "How does NASA organize a party? They planet.",
  "Why can’t you trust an atom? Because they make up everything.",
  "What do you call a group of disorganized cats? A cat-tastrophe.",
  "Where do you learn to make banana splits? At sundae school.",
  "What happens to a frog’s car when it breaks down? It gets toad away.",
  "How do trees access the internet? They log in.",
  "Why did the painting go to jail?  It was framed.",
  "Helvetica and Times New Roman walk into a bar. The bartender says, “We don’t serve your type.”",
  "What did the fish say when he swam into a wall? Dam.",
  "Did you hear about the Italian chef who died? He pasta-way.",
  "Do you want to hear a construction joke? Sorry, I’m still working on it.",
  "Why should you never trust stairs? They’re always up to something.",
  "Did you know – it’s impossible to lick your elbow. You’re probably trying it, anyway!",
  "The very first movie to show a toilet being flushed was Alfred Hitchcock’s classic horror picture, Psycho.",
  "It’s estimated that the average fart travels at a speed of 7 miles per hour!",
  "There is a street in Valladolid, in Spain – Calle Me Falta un Tornillo – which translates roughly to ‘I’ve Got a Screw Loose Street’.",
  "No one is entirely sure why duck quacks produce no echoes.",
  "Bank robberies, apparently, are weekend pursuits. Statistics show that over 50% of them take place on a Friday!",
  "Believe it or not, money was actually printed on wood for a time in the US! And today, the dollar’s not actually made of paper at all – they’re made of linen!",
  "There’s a Christmas tradition in Spain where a character called the ‘pooping log’ excretes presents – and you thought a fat guy coming down the chimney was weird enough!",
  "The ancient Greeks, apparently, used to throw apples at each other to show that they loved them.",
  "If you tilt your head back and pretend to shake salt, you can actually taste the salt.",
  "Your thumb is the same length as your nose.",
  "Farting consistently for 6 years and 9 months will produce enough gas to make an atomic bomb.",
  "You will know if it’s cold outside if you go outside and feel cold!",
  "Our language is called the mother tongue because the father never gets a chance to speak.",
  "You definitely can’t buy love but damn, you can pay a heavy price for it!",
  "It takes about 4 seconds for silence to become awkward!",
  "Playing music next to a flower will make it grow faster.",
);
var puns = function () {
  var newpun = punsarray[Math.floor(Math.random() * punsarray.length)];
  document.getElementById("laugh-text").innerHTML = newpun;
};
