var punsarray = Array(
  "Why did the scarecrow win an award? Because he was outstanding in his field.",
  "Why did the melon jump into the lake? It wanted to be a water-melon.",
  "How does the ocean say hello? It waves.",
  "What creature is smarter than a talking parrot? A spelling bee.",
  "Apparently, you can’t use “beef stew” as a password. It’s not stroganoff.",
  "Why did the drum take a nap? It was beat.",
  "Where do hamburgers go dancing?  They go to the meat-ball.",
  "Why did the tomato turn red?  It saw the salad dressing.",
  "Why shouldn’t you write with a broken pencil? Because it’s pointless.",
  "What do you call two monkeys that share an Amazon account? Prime mates.",
  "How does NASA organize a party? They planet.",
  "Why can’t you trust an atom? Because they make up everything.",
  "What do you call a group of disorganized cats? A cat-tastrophe.",
  "Where do you learn to make banana splits? At sundae school.",
  "What happens to a frog’s car when it breaks down? It gets toad away.",
  "How do trees access the internet? They log in.",
  "Why did the painting go to jail?  It was framed.",
  "Helvetica and Times New Roman walk into a bar. The bartender says, “We don’t serve your type.”",
  "What did the fish say when he swam into a wall? Dam.",
  "Did you hear about the Italian chef who died? He pasta-way.",
  "Do you want to hear a construction joke? Sorry, I’m still working on it.",
  "Why should you never trust stairs? They’re always up to something.",
  "Did you know – it’s impossible to lick your elbow. You’re probably trying it, anyway!",
  "The very first movie to show a toilet being flushed was Alfred Hitchcock’s classic horror picture, Psycho.",
  "It’s estimated that the average fart travels at a speed of 7 miles per hour!",
  "There is a street in Valladolid, in Spain – Calle Me Falta un Tornillo – which translates roughly to ‘I’ve Got a Screw Loose Street’.",
  "No one is entirely sure why duck quacks produce no echoes.",
  "Bank robberies, apparently, are weekend pursuits. Statistics show that over 50% of them take place on a Friday!",
  "Believe it or not, money was actually printed on wood for a time in the US! And today, the dollar’s not actually made of paper at all – they’re made of linen!",
  "There’s a Christmas tradition in Spain where a character called the ‘pooping log’ excretes presents – and you thought a fat guy coming down the chimney was weird enough!",
  "The ancient Greeks, apparently, used to throw apples at each other to show that they loved them.",
  "If you tilt your head back and pretend to shake salt, you can actually taste the salt.",
  "Your thumb is the same length as your nose.",
  "Farting consistently for 6 years and 9 months will produce enough gas to make an atomic bomb.",
  "You will know if it’s cold outside if you go outside and feel cold!",
  "Our language is called the mother tongue because the father never gets a chance to speak.",
  "You definitely can’t buy love but damn, you can pay a heavy price for it!",
  "It takes about 4 seconds for silence to become awkward!",
  "Playing music next to a flower will make it grow faster.",
  "Why did Adele cross the road? To say hello from the other side.",
  "To the guy who invented zero, thanks for nothing.",
  "Can February March? No, but April May.",
  "Need an ark to save two of every animal? I noah guy.",
  "A man sued an airline company after it lost his luggage. Sadly, he lost his case.",
  "I lost my mood ring and I don't know how to feel about it!",
  "I was wondering why the ball was getting bigger. Then it hit me.",
  "Waking up this morning was an eye-opening experience.",
  "What do you use to cut a Roman Emperor's hair? Ceasers.",
  "England doesn't have a kidney bank, but it does have a Liverpool.",
  "A cross-eyed teacher couldn’t control his pupils.",
  "German sausage jokes are just the wurst.",
  "What do you call an alligator in a vest? An investigator.",
  "I bought a boat because it was for sail.",
  "Why didn't the cat go to the vet? He was feline fine!",
  "What should a lawyer always wear to a court? A good lawsuit!",
  "The past, the present, and the future walk into a bar. It was tense!",
  "You really shouldn't be intimidated by advanced math… it's easy as pi!",
  "Towels can’t tell jokes. They have a dry sense of humor.",
  "Why should you never trust a train? They have loco motives.",
  "I wanted to buy a pair of camouflage pants, but I couldn't find any.",
  "Why are elevator jokes so classic and good? They work on many levels.",
  "I had a taser once. It was stunning.",
  "Know any good rope jokes? I'm a frayed knot.",
  "Why shouldn't you argue with a dinosaur? You'll get jurasskicked.",
  "I'm afraid of speed bumps, but I'm slowly getting over it.",
  "Why couldn't the bike stand up? It was two-tired.",
  "I wrote a song about burritos. It's a rap.",
  "Why don't pirates know the alphabet? Because they keep getting lost at C.",
  "How did the barber win the race? He knew a shortcut.",
  "Making mirrors is a job I can really see myself doing.",
  "What do you call fake noodles? Impastas.",
  "Why is bread so lazy? It's always loafin' around.",
  "We were going to tell you a pizza joke, but it's too cheesy.",
  "Let's give 'em something to taco 'bout.",
  "You're pre-tea cute.",
  "Two kittens had an argument. It was a cat-astrophe.",
  "What kind of drink can be bitter and sweet? Reali-tea.",
  "Why do bees have sticky hair? Because they use a honeycomb.",
  "What’s the most detail-oriented ocean? The Pacific.",
  "When does a joke become a “dad joke?” When it becomes apparent.",
  "Why did the man fall down the well? Because he couldn’t see that well.",
  "Why did the coach go to the bank? To get his quarterback.",
  "How do celebrities stay cool? They have many fans.",
  "Sundays are always a little sad, but the day before is a sadder day.",
  "5/4 of people admit they’re bad at fractions.",
  "Singing in the shower is fun until you get soap in your mouth. Then it becomes a soap opera.",
  "I lost my job at the bank on my first day. A dude asked me to check their balance, so I pushed them over.",
  "How does a penguin build his house? Igloos it together.",
  "Stop looking for the perfect match…use a lighter.",
);
var puns = function () {
  var newpun = punsarray[Math.floor(Math.random() * punsarray.length)];
  document.getElementById("laugh-text").innerHTML = newpun;
};
