var punsarray = Array(
  "Why did the scarecrow win an award? Because he was outstanding in his field.",
  "Why did the melon jump into the lake? It wanted to be a water-melon.",
  "How does the ocean say hello? It waves.",
  "What creature is smarter than a talking parrot? A spelling bee.",
  "Apparently, you can’t use “beef stew” as a password. It’s not stroganoff.",
  "Why did the drum take a nap? It was beat.",
  "Where do hamburgers go dancing?  They go to the meat-ball.",
  "Why did the tomato turn red?  It saw the salad dressing.",
  "Why shouldn’t you write with a broken pencil? Because it’s pointless.",
  "What do you call two monkeys that share an Amazon account? Prime mates.",
  "How does NASA organize a party? They planet.",
  "Why can’t you trust an atom? Because they make up everything.",
  "What do you call a group of disorganized cats? A cat-tastrophe.",
  "Where do you learn to make banana splits? At sundae school.",
  "What happens to a frog’s car when it breaks down? It gets toad away.",
  "How do trees access the internet? They log in.",
  "Why did the painting go to jail?  It was framed.",
  "Helvetica and Times New Roman walk into a bar. The bartender says, “We don’t serve your type.”",
  "What did the fish say when he swam into a wall? Dam.",
  "Did you hear about the Italian chef who died? He pasta-way.",
  "Do you want to hear a construction joke? Sorry, I’m still working on it.",
  "Why should you never trust stairs? They’re always up to something.",
  "Did you know – it’s impossible to lick your elbow. You’re probably trying it, anyway!",
  "The very first movie to show a toilet being flushed was Alfred Hitchcock’s classic horror picture, Psycho.",
  "It’s estimated that the average fart travels at a speed of 7 miles per hour!",
  "There is a street in Valladolid, in Spain – Calle Me Falta un Tornillo – which translates roughly to ‘I’ve Got a Screw Loose Street’.",
  "No one is entirely sure why duck quacks produce no echoes.",
  "Bank robberies, apparently, are weekend pursuits. Statistics show that over 50% of them take place on a Friday!",
  "Believe it or not, money was actually printed on wood for a time in the US! And today, the dollar’s not actually made of paper at all – they’re made of linen!",
  "There’s a Christmas tradition in Spain where a character called the ‘pooping log’ excretes presents – and you thought a fat guy coming down the chimney was weird enough!",
  "The ancient Greeks, apparently, used to throw apples at each other to show that they loved them.",
  "If you tilt your head back and pretend to shake salt, you can actually taste the salt.",
  "Your thumb is the same length as your nose.",
  "Farting consistently for 6 years and 9 months will produce enough gas to make an atomic bomb.",
  "You will know if it’s cold outside if you go outside and feel cold!",
  "Our language is called the mother tongue because the father never gets a chance to speak.",
  "You definitely can’t buy love but damn, you can pay a heavy price for it!",
  "It takes about 4 seconds for silence to become awkward!",
  "Playing music next to a flower will make it grow faster.",
  "Why did Adele cross the road? To say hello from the other side.",
  "To the guy who invented zero, thanks for nothing.",
  "Can February March? No, but April May.",
  "Need an ark to save two of every animal? I noah guy.",
  "A man sued an airline company after it lost his luggage. Sadly, he lost his case.",
  "I lost my mood ring and I don't know how to feel about it!",
  "I was wondering why the ball was getting bigger. Then it hit me.",
  "Waking up this morning was an eye-opening experience.",
  "What do you use to cut a Roman Emperor's hair? Ceasers.",
  "England doesn't have a kidney bank, but it does have a Liverpool.",
  "A cross-eyed teacher couldn’t control his pupils.",
  "German sausage jokes are just the wurst.",
  "What do you call an alligator in a vest? An investigator.",
  "I bought a boat because it was for sail.",
  "Why didn't the cat go to the vet? He was feline fine!",
  "What should a lawyer always wear to a court? A good lawsuit!",
  "The past, the present, and the future walk into a bar. It was tense!",
  "You really shouldn't be intimidated by advanced math… it's easy as pi!",
  "Towels can’t tell jokes. They have a dry sense of humor.",
  "Why should you never trust a train? They have loco motives.",
  "I wanted to buy a pair of camouflage pants, but I couldn't find any.",
  "Why are elevator jokes so classic and good? They work on many levels.",
  "I had a taser once. It was stunning.",
  "Know any good rope jokes? I'm a frayed knot.",
  "Why shouldn't you argue with a dinosaur? You'll get jurasskicked.",
  "I'm afraid of speed bumps, but I'm slowly getting over it.",
  "Why couldn't the bike stand up? It was two-tired.",
  "I wrote a song about burritos. It's a rap.",
  "Why don't pirates know the alphabet? Because they keep getting lost at C.",
  "How did the barber win the race? He knew a shortcut.",
  "Making mirrors is a job I can really see myself doing.",
  "What do you call fake noodles? Impastas.",
  "Why is bread so lazy? It's always loafin' around.",
  "We were going to tell you a pizza joke, but it's too cheesy.",
  "Let's give 'em something to taco 'bout.",
  "You're pre-tea cute.",
  "Two kittens had an argument. It was a cat-astrophe.",
  "What kind of drink can be bitter and sweet? Reali-tea.",
  "Why do bees have sticky hair? Because they use a honeycomb.",
  "What’s the most detail-oriented ocean? The Pacific.",
  "When does a joke become a “dad joke?” When it becomes apparent.",
  "Why did the man fall down the well? Because he couldn’t see that well.",
  "Why did the coach go to the bank? To get his quarterback.",
  "How do celebrities stay cool? They have many fans.",
  "Sundays are always a little sad, but the day before is a sadder day.",
  "5/4 of people admit they’re bad at fractions.",
  "Singing in the shower is fun until you get soap in your mouth. Then it becomes a soap opera.",
  "I lost my job at the bank on my first day. A dude asked me to check their balance, so I pushed them over.",
  "How does a penguin build his house? Igloos it together.",
  "Stop looking for the perfect match…use a lighter.",
  "I'm afraid for the calendar. Its days are numbered.",
  "My wife said I should do lunges to stay in shape. That would be a big step forward.",
  "Why do fathers take an extra pair of socks when they go golfing? In case they get a hole in one!",
  "Singing in the shower is fun until you get soap in your mouth. Then it's a soap opera.",
  "What do you call a fish wearing a bowtie? Sofishticated.",
  "I thought the dryer was shrinking my clothes. Turns out it was the refrigerator all along.",
  "Dear Math, grow up and solve your own problems.",
  "Why do seagulls fly over the ocean? Because if they flew over the bay, we'd call them bagels.",
  "What did one wall say to the other? I'll meet you at the corner.",
  "Where do boats go when they're sick? To the boat doc.",
  "How do you get a squirrel to like you? Act like a nut.",
  "What did one hat say to the other? Stay here! I'm going on ahead.",
  "This graveyard looks overcrowded. People must be dying to get in.",
  "What kind of car does an egg drive? A yolkswagen.",
  "How do you make 7 even? Take away the s.",
  "Do you wanna box for your leftovers? No, but I'll wrestle you for them.",
  "Shout out to your fingers. You can count on all of them.",
  "What country's capital is growing the fastest? Ireland. Every day it's Dublin.",
  "Hunting unicorns is legal in Michigan.",
  "Cows moo with regional accents.",
  "Almost 30,000 rubber duckies were lost at sea in the 90s.",
  "A single strand of spaghetti is technically called a ‘spaghetto’",
  "Light travels faster than sound. That's why some people appear bright until you hear them speak.",
  "I have a few jokes about unemployed people, but none of them work.",
  "A police officer just knocked on my door and told me my dogs are chasing people on bikes. That’s ridiculous. My dogs don’t even own bikes.",
  "I went to buy some camouflage trousers yesterday but couldn't find any.",
  "Heard about the new restaurant called Karma? There’s no menu - you get what you deserve.",
  "What do you call a bee that can’t make up its mind? A maybe.",
  "Jane broke her finger today, but on the other hand she was completely fine",
  "When everything is coming your way, you're in the wrong lane.",
  "All chemists know that alcohol is always a solution.",
  "The furniture store keeps calling me to come back. But all I wanted was one night stand.",
  "I wasn’t originally going to get a brain transplant, but then I changed my mind.",
  "What washes up on tiny beaches? Microwaves.",
  "How does an attorney sleep? First he lies on one side, then he lies on the other.",
  "What are the strongest days of the week? Saturday and Sunday, the rest are weekdays.",
  "The guy who invented the door knocker got a no-bell prize.",
  "Sleeping comes so naturally to me, I could do it with my eyes closed.",
  "We tried to make a chemistry joke, but got no reaction.",
  "I'm on a seafood diet. Every time I see food, I eat it.",
  "Why are frogs so happy? They eat whatever bugs them.",
  "The machine at the coin factory just suddenly stopped working, with no explanation. It doesn’t make any cents.",
  "What do you call a super articulate dinosaur? A Thesaurus.",
  "I'm not a doctor but I'm losing my patience.",
  "Why would you stand in a corner if it is 90 degrees? That's way too hot.",
  "What do you call nitrogen when the sun comes up? Daytrogen.",
  "One bird can't make a pun. But toucan.",
  "Orion’s Belt is a waist of space.",
  "We ordered Chinese food and it didn’t come with any cookies and I can’t stop talking about how unfortunate this is.",
  "Have you ever noticed that Ireland is just one sea away from Iceland?",
  "Did you hear the one about the roof? Never mind, it's over your head.",
  "Why did the golfer wear two pairs of pants? In case he got a hole in one.",
  "What do you call a deer with no eyes? No idear.",
  "What lights up a soccer stadium? A soccer match.",
  "Why couldn’t the leopard play hide and seek? Because he was always spotted.",
  "How does a man on the moon cut his hair? Eclipse it.",
  "Why do you never see elephants hiding in trees? Because they're so good at it.",
  "What do you call a guy with a rubber toe? Roberto.",
  "I got a hen to regularly count her own eggs. She's a real mathamachicken.",
  "What do you call a donkey with only three legs? A wonkey.",
  "An apple a day keeps the doctor away. At least it does if you throw it hard enough.",
  "How many apples grow on a tree? All of them.",
  "Did you hear the rumor about butter? Well, we're not going to spread it.",
  "Why did the old man fall into the well? Because he couldn't see that well.",
  "A witch's vehicle goes brrrroom brrrroom",
  "The wedding was so beautiful, even the cake was in tiers.",
  "If you see a robbery at an Apple Store does that make you an iWitness?",
  "Why couldn't the astronaut land on the moon? Because it was full.",
  "What do you call a shoe made of a banana? A slipper.",
  "Why do dogs float in water? Because they are good buoys.",
  "What do you call a beehive without an exit? Unbelievable.",
  "What do you call cheese that isn't yours? Nacho cheese.",
  "What's orange and sounds like a parrot? A carrot.",
  "Did you hear about the bacon cheeseburger who couldn't stop telling jokes? It was on a roll.",
  "What do you call a sad cup of coffee? Depresso.",
  "What rock group has four men that don't sing? Mount Rushmore.",
  "Just ordered a chicken and an egg online. We'll let you know.",
  "Did you hear about the restaurant on the moon? Great food, no atmosphere.",
  "What's the difference between a poorly-dressed man on a tricycle and a well-dressed man on a bicycle? Attire.",
  "Last night I had a dream that I weighed less than a thousandth of a gram. I was like, 0mg.",
  "Within minutes, the detectives knew what the murder weapon was. It was a brief case.",
  "Justice is a dish best-served cold. If it were served warm, it would be justwater.",
  "Did you hear about the ATM that got addicted to money? It suffered from withdrawals.",
  "What has four wheels and flies? A garbage truck.",
  "So a vowel saves another vowel's life. The other vowel says, “Aye E. I owe you.”",
  "Someone complimented my parking today. They left a sweet note on my windshield that said “parking fine.”",
  "What do scholars eat when they're hungry? Academia nuts.",
  "What do you call it when a group of apes starts a company? Monkey business.",
  "What did the police officer say to their belly-button? You’re under a vest.",
  "What did Tennessee? The same thing as Arkansas.",
  "How can you tell it’s a dogwood tree? By the bark.",
  "Our vacuum cleaner is getting old. It's just gathering dust.",
  "Which state has the most streets? Rhode Island.",
  "Why was the color green notoriously single? It was always so jaded.",
  "Why were the utensils stuck together? They were spooning.",
  "What does a house wear? Address",
  "What do you call someone who won't stick to a diet? A desserter.",
  "What did the two pieces of bread say on their wedding day? It was loaf at first sight.",
  "What did the drummer call his twin daughters? Anna One, Anna Two!",
  "Two goldfish are in a tank. One says to the other, “Do you know how to drive this thing?”",
);
var puns = function () {
  var newpun = punsarray[Math.floor(Math.random() * punsarray.length)];
  document.getElementById("laugh-text").innerHTML = newpun;
  document.getElementById("sharepun").value = newpun;
};
